language: ruby
cache: bundler

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

branches:
  only:
    - master

bundler_args: --jobs 7 --retry 3

matrix:
  include:
    - rvm: 3.0.0
    - env: "GEMFILE_MOD=\"gem 'chef', '= 16.9.32'\""
      rvm: 2.7.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 16.8.14'\""
      rvm: 2.7.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 16.7.61'\""
      rvm: 2.7.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 16.6.14'\""
      rvm: 2.7.2
    - env: "GEMFILE_MOD=\"gem 'chef', '= 16.5.77'\""
      rvm: 2.7.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 15.15.0'\""
      rvm: 2.6.6
    - env: "GEMFILE_MOD=\"gem 'chef', '= 15.0.300'\""
      rvm: 2.6.3
